import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jaimefreire' at '9/11/16 6:48 PM' with Gradle 3.0
 *
 * @author jaimefreire, @date 9/11/16 6:48 PM
 */
public class AbstractFactoryTest {
    @Test public void testSomeLibraryMethod() {
        Main classUnderTest = new Main();

    }
}
